name: Comment when opened
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 19
        uses: actions/setup-node@v2
        with:
          node-version: "19"
      - run: npm install
      